mcw/backup/__init__.py
from collections import defaultdict, namedtuple
from datetime import datetime, timedelta
import os.path
import shelve
import glob
import os

from werkzeug import secure_filename
import gevent.subprocess
import gevent.pool
import gevent

from mcw.signals import on_backup_started, on_backup_stopped, on_backup_deleted
from mcw.utils.store import JsonStore


BackupJob = namedtuple('BackupJob', ['name', 'delta', 'num'])
BackupFile = namedtuple('BackupFile', ['name', 'date', 'size'])


class Backup(object):
    EXTENSION = None

    FORMAT = '%Y-%m-%dT%H:%M:%S'
    BACKUPS = [
        BackupJob('hourly', timedelta(hours=1), 6),
        BackupJob('daily', timedelta(days=1), 7),
        BackupJob('weekly', timedelta(weeks=1), 4),
        BackupJob('monthly', timedelta(weeks=4), 2)
    ]

    def __init__(self, minecraft, path, worldonly=True, world=None):
        self.minecraft = minecraft
        self.path = path
        self.worldonly = worldonly
        self.world = world
        if world is None or world.strip().lower() == '*guess*':
            self.world = self.minecraft.server_properties['level-name']
        self.source = self.minecraft.path

        if not os.path.exists(self.source):
            raise ValueError('Source folder for backups does not exist')

        if not os.path.exists(self.path):
            raise ValueError('Destination folder for backups does not exist')

        self._last = os.path.join(self.path, 'server')
        if not os.path.exists(self._last):
            os.makedirs(self._last)

        self.metadata = JsonStore(os.path.join(path, 'metadata.json'))

        self._pool = gevent.pool.Pool()
        self._in_backup = False
        self._processes = list()

    @classmethod
    def collect_backups(cls, path):
        files = os.path.join(path, 'backup-*-*.{0}'.format(cls.EXTENSION))

        backups = defaultdict(list)
        for backup in sorted(glob.glob(files)):
            size = os.path.getsize(backup)
            name = os.path.split(backup)[1]
            try:
                _, type, date = name.split('-', 2)
                date = date.split('.', 1)[0]
                date = datetime.strptime(date, cls.FORMAT)
            except (ValueError, IndexError):
                continue
            backups[type].append(BackupFile(name, date, size))

        return backups

    @classmethod
    def get_backup_name(cls, name, dt=None):
        if dt is None:
            dt = datetime.now()

        return 'backup-{}-{}'.format(name, dt.strftime(cls.FORMAT))

    @property
    def is_idle(self):
        # all unfinished processes
        self._processes = [p for p in self._processes if p.poll() is None]
        # not _in_backup and no process running
        return not self._in_backup and len(self._processes) == 0

    def get_backups(self):
        ret = defaultdict(list)
        for type, backups in self.collect_backups(self.path).items():
            for backup in backups:
                label = type
                if backup.name in self.metadata:
                    label = self.metadata[backup.name]

                ret[type].append({
                    'name': backup.name, 'date': backup.date,
                    'size': backup.size, 'label': label
                })
        return ret

    def get_label(self, name):
        if name in self.metadata:
            return self.metadata[name]
        return None

    def delete_backup(self, name):
        if not name.endswith(self.EXTENSION):
            raise ValueError('invalid name')

        names = os.listdir(self.path)
        if name not in names:
            raise KeyError('backup does not exist')

        os.remove(os.path.join(self.path, name))
        on_backup_deleted.send(self, name=name)

    def start(self, delay=600):
        def exc(gr):
            self._in_backup = False

        g = gevent.spawn_later(delay, self.run)
        g.link_exception(exc)
        self._pool.add(g)

    def run(self):
        self._in_backup = True

        backups = self.collect_backups(self.path)
        for job in self.BACKUPS:
            past = [b.date for b in backups.get(job.name, [])]
            self.create_backup_if_required(job, past)

        self._in_backup = False

        def exc(gr):
            self._in_backup = False

        g = gevent.spawn_later(3600, self.run)
        g.link_exception(exc)
        self._pool.add(g)

    def create_backup_if_required(self, job, past, force=False):
        if not self.minecraft.is_running and not force:
            return

        now = datetime.now()
        # past has to be sorted
        last = past[-1] if past else datetime.min

        if now - last > job.delta or force:
            # we make a new backup, add it to the past list
            past.append(self.create_backup(job.name)[0])
            # only a maximum number of backups allowed, remove
            # too old backups
            self.remove_old_backups(job, past)

    def create_user_backup(self, label):
        time, name = self.create_backup('user', label)

    def create_backup(self, type, label=None):
        raise NotImplementedError()

    def remove_old_backups(self, job, past):
        to_delete = past[:max(0, len(past)-job.num)]

        for dt in to_delete:
            name = '{0}.{1}'.format(
                self.get_backup_name(job.name, dt), self.EXTENSION
            )
            os.remove(os.path.join(self.path, name))

mcw/views/index.py
from flask import (
    Blueprint, request, session, g, render_template,
    url_for, redirect, abort, jsonify, current_app
)

index = Blueprint('index', __name__)


MENUS = [
    ('overview', 'Overview', 'fa fa-line-chart', 'overview.html'),
    ('console', 'Console', 'fa fa-terminal', 'console.html'),
    ('backups', 'Backups', 'fa fa-hdd-o', 'backups.html')
]


@index.route('/')
def site_index():
    if not session.get('loggedin', False):
        return render_template('login.html')

    return render_template(
        'backend.html', menus=MENUS, default='overview',
        backups=g.backup.get_backups()
    )


@index.route('/login', methods=['POST'])
def login():
    pw = request.form.get('password', None)

    if pw == current_app.config.password:
        session['loggedin'] = True
        return jsonify({'success': True})

    return jsonify({
        'success': False, 'error': 'Login Failed: Invalid password'
    })


@index.route('/logout')
def logout():
    if session.get('loggedin', False):
        session['loggedin'] = False
        return redirect(url_for('index.site_index'))

    return abort(401)

mcw/templates/backend.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

            <title>{% block title %}[MCW] Admin Panel{% endblock %}</title>
            <script src="/static/js/jquery-1.11.2.min.js"></script>
            <script src="/static/js/socket.io.min.js"></script>
            <script src="/static/js/d3.min.js"></script>
            <script src="/static/js/epoch.js"></script>
            <script src="/static/js/tablesort.js"></script>
            <script src="/static/js/backend.js"></script>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="/static/css/epoch.min.css">
            <link rel="stylesheet" href="/static/css/tablesort.css">
            <link rel="stylesheet" href="/static/css/common.css">
            <link rel="stylesheet" href="/static/css/backend.css">
        {% endblock %}
    </head>
    <body>
        <header>
            <nav>
                <i class="fa fa-sign-out"></i>
                <a href="{{ url_for('index.logout') }}">Logout</a>
            </nav>
            <div>MCW Admin Panel</div>
        </header>

            <nav>
                <ul>
                    {% for id, name, icon, template in menus %}
                    <li class="{{ 'active' if id==default }}">
                        {% if icon %}<i class="{{ icon }}"></i>&nbsp;&nbsp;{% endif %}
                        <a href="#{{ id }}">{{ name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </nav>


            <main>
                <article class="statusbar">
                    <p class=".form-control-static">Status:</p>
                    <label class="label label-warning status-webpanel">Webpanel: <span class="status">Unknown</span></label>
                    <label class="label label-warning status-server">Server: <span class="status">Unknown</span></label>
                    <label class="label label-warning status-uptime">Uptime: <span class="status">?</span></label>
                    <label class="label label-warning status-player">Player: <span class="status">?/?</span></label>
                </article>

                {% for id, name, icon, template in menus %}
                <section id="{{ id }}_inner">{% include template %}</section>
                {% endfor %}
            </main>
    </body>
</html>

mcw/templates/backups.html
<article class="backup-alerts">
</article>

<article>
    <h3 class="bb">Scheduled:</h3>
    <div class="backup-table-outer">
        <table width="100%" id="backup-schedule">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Label</th>
                    <th>Size</th>
                    <th class="no-sort"></th>
                </tr>
            </thead>
            <tbody>
                {% set notempty = [] %}
                {% for type in ['monthly', 'weekly', 'daily', 'hourly'] %}
                {% set outer_loop = loop %}
                {% for backup in backups[type] %}
                <tr data-name="{{ backup.name }}">
                    <td data-sort="{{ backup.date|mktime }}">{{ backup.date.strftime('%c') }}</td>
                    <td data-sort="{{ outer_loop.index }}.{{backup.date|mktime|int}}">{{ backup.label }}</td>
                    <td data-sort="{{ backup.size }}">{{ backup.size | sizeof_fmt }}</td>
                    <td><a class="backup-delete" href="javascript:void(0);"><i class="fa fa-times-circle"></i></a></td>
                </tr>
                {% if notempty.append(True) %} {% endif %}
                {% endfor %}
                {% endfor %}
                {% if not notempty %}
                <tr class="no-sort"><td style="color: red">No backups found</td><td></td><td></td><td></td></tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</article>

<article>
    <h3 class="bb">Custom:</h3>
    <div class="backup-table-outer">
        <table width="100%" id="backup-user">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Label</th>
                    <th>Size</th>
                    <th class="no-sort"></th>
                </tr>
            </thead>
            <tbody>
                {% for backup in backups['user'] %}
                <tr data-name="{{ backup.name }}">
                    <td data-sort="{{ backup.date|mktime }}">{{ backup.date.strftime('%c') }}</td>
                    <td>{{ backup.label }}</td>
                    <td data-sort="{{ backup.size }}">{{ backup.size | sizeof_fmt }}</td>
                    <td><a class="backup-delete" href="javascript:void(0);"><i class="fa fa-times-circle"></i></a></td>
                </tr>
                {% else %}
                <tr class="no-sort"><td style="color: red">No backups found</td><td></td><td></td><td></td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</article>

<article>
    <!--<h3 class="bb">Create Backup:</h3>-->
    <div class="backup-create">
        <label>Label:</label>
        <input type="text">
        <button class="btn btn-primary backup-new" disabled>Create Backup</button>
    </div>
</article>

mcw/templates/console.html
<article class="server-buttons">
    <!--<div class="btn-group" role="group" aria-label="...">-->
        <button type="button" class="btn btn-success server-start" disabled>Start</button>
        <button type="button" class="btn btn-danger server-stop" disabled>Stop</button>
        <button type="button" class="btn btn-warning server-restart" disabled>Restart</button>
    <!--</div>-->
</article>

<article>
    <div class="console ui-widget-content">
    </div>

    <input type="text" class="command-input">
</article>

mcw/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

            <title>{% block title %}[MCW] Login{% endblock %}</title>
            <script src="/static/js/jquery-1.11.2.min.js"></script>
            <script src="/static/js/login.js"></script>
            <link rel="stylesheet" href="/static/css/common.css">
            <link rel="stylesheet" href="/static/css/login.css">
        {% endblock %}
    </head>

    <body>
        <main>
            <section>
                <header>
                    <h1>Login</h1>
                </header>

                <input id="password" type="password">

                <footer>
                    <aside>This site requires JavaScript</aside>
                </footer>
            </section>
        </main>
    </body>
</html>

mcw/templates/overview.html
<article>
    <h3>CPU Usage:</h3>
    <div id="cpu-graph" class="epoch"></div>
</article>

<article>
    <h3>Memory Usage:</h3>
    <div id="memory-graph" class="epoch"></div>
</article>

mcw/templates/status.html
<article class="server-buttons">
    <!--<div class="btn-group" role="group" aria-label="...">-->
        <button type="button" class="btn btn-success server-start" disabled>Start</button>
        <button type="button" class="btn btn-danger server-stop" disabled>Stop</button>
        <button type="button" class="btn btn-warning server-restart" disabled>Restart</button>
    <!--</div>-->
</article>

<article>
    <div class="console ui-widget-content">
    </div>

    <input type="text" class="command-input">
</article>